# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_nativebt')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_nativebt')
    _nativebt = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_nativebt', [dirname(__file__)])
        except ImportError:
            import _nativebt
            return _nativebt
        try:
            _mod = imp.load_module('_nativebt', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _nativebt = swig_import_helper()
    del swig_import_helper
else:
    import _nativebt
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def _bt_python_field_listcaller(ctf_event, scope):
    return _nativebt._bt_python_field_listcaller(ctf_event, scope)
_bt_python_field_listcaller = _nativebt._bt_python_field_listcaller

def _bt_python_field_one_from_list(list, index):
    return _nativebt._bt_python_field_one_from_list(list, index)
_bt_python_field_one_from_list = _nativebt._bt_python_field_one_from_list

def _bt_python_event_decl_listcaller(handle_id, ctx):
    return _nativebt._bt_python_event_decl_listcaller(handle_id, ctx)
_bt_python_event_decl_listcaller = _nativebt._bt_python_event_decl_listcaller

def _bt_python_decl_one_from_list(list, index):
    return _nativebt._bt_python_decl_one_from_list(list, index)
_bt_python_decl_one_from_list = _nativebt._bt_python_decl_one_from_list

def _by_python_field_decl_listcaller(event_decl, scope):
    return _nativebt._by_python_field_decl_listcaller(event_decl, scope)
_by_python_field_decl_listcaller = _nativebt._by_python_field_decl_listcaller

def _bt_python_field_decl_one_from_list(list, index):
    return _nativebt._bt_python_field_decl_one_from_list(list, index)
_bt_python_field_decl_one_from_list = _nativebt._bt_python_field_decl_one_from_list

def _bt_python_get_array_from_def(field):
    return _nativebt._bt_python_get_array_from_def(field)
_bt_python_get_array_from_def = _nativebt._bt_python_get_array_from_def

def _bt_python_get_sequence_from_def(field):
    return _nativebt._bt_python_get_sequence_from_def(field)
_bt_python_get_sequence_from_def = _nativebt._bt_python_get_sequence_from_def

def _bt_python_get_array_element_declaration(field):
    return _nativebt._bt_python_get_array_element_declaration(field)
_bt_python_get_array_element_declaration = _nativebt._bt_python_get_array_element_declaration

def _bt_python_get_sequence_element_declaration(field):
    return _nativebt._bt_python_get_sequence_element_declaration(field)
_bt_python_get_sequence_element_declaration = _nativebt._bt_python_get_sequence_element_declaration

def _bt_python_get_array_string(field):
    return _nativebt._bt_python_get_array_string(field)
_bt_python_get_array_string = _nativebt._bt_python_get_array_string

def _bt_python_get_sequence_string(field):
    return _nativebt._bt_python_get_sequence_string(field)
_bt_python_get_sequence_string = _nativebt._bt_python_get_sequence_string

def _bt_python_field_integer_get_signedness(field):
    return _nativebt._bt_python_field_integer_get_signedness(field)
_bt_python_field_integer_get_signedness = _nativebt._bt_python_field_integer_get_signedness

def _bt_python_get_field_type(field):
    return _nativebt._bt_python_get_field_type(field)
_bt_python_get_field_type = _nativebt._bt_python_get_field_type

def _bt_python_ctf_field_type_enumeration_get_mapping(enumeration, index):
    return _nativebt._bt_python_ctf_field_type_enumeration_get_mapping(enumeration, index)
_bt_python_ctf_field_type_enumeration_get_mapping = _nativebt._bt_python_ctf_field_type_enumeration_get_mapping

def _bt_python_ctf_field_type_enumeration_get_mapping_unsigned(enumeration, index):
    return _nativebt._bt_python_ctf_field_type_enumeration_get_mapping_unsigned(enumeration, index)
_bt_python_ctf_field_type_enumeration_get_mapping_unsigned = _nativebt._bt_python_ctf_field_type_enumeration_get_mapping_unsigned

def _bt_python_ctf_field_type_structure_get_field_name(structure, index):
    return _nativebt._bt_python_ctf_field_type_structure_get_field_name(structure, index)
_bt_python_ctf_field_type_structure_get_field_name = _nativebt._bt_python_ctf_field_type_structure_get_field_name

def _bt_python_ctf_field_type_structure_get_field_type(structure, index):
    return _nativebt._bt_python_ctf_field_type_structure_get_field_type(structure, index)
_bt_python_ctf_field_type_structure_get_field_type = _nativebt._bt_python_ctf_field_type_structure_get_field_type

def _bt_python_ctf_field_type_variant_get_field_name(variant, index):
    return _nativebt._bt_python_ctf_field_type_variant_get_field_name(variant, index)
_bt_python_ctf_field_type_variant_get_field_name = _nativebt._bt_python_ctf_field_type_variant_get_field_name

def _bt_python_ctf_field_type_variant_get_field_type(variant, index):
    return _nativebt._bt_python_ctf_field_type_variant_get_field_type(variant, index)
_bt_python_ctf_field_type_variant_get_field_type = _nativebt._bt_python_ctf_field_type_variant_get_field_type

def _bt_python_ctf_event_class_get_field_name(event_class, index):
    return _nativebt._bt_python_ctf_event_class_get_field_name(event_class, index)
_bt_python_ctf_event_class_get_field_name = _nativebt._bt_python_ctf_event_class_get_field_name

def _bt_python_ctf_event_class_get_field_type(event_class, index):
    return _nativebt._bt_python_ctf_event_class_get_field_type(event_class, index)
_bt_python_ctf_event_class_get_field_type = _nativebt._bt_python_ctf_event_class_get_field_type

def _bt_python_ctf_clock_get_uuid_index(clock, index):
    return _nativebt._bt_python_ctf_clock_get_uuid_index(clock, index)
_bt_python_ctf_clock_get_uuid_index = _nativebt._bt_python_ctf_clock_get_uuid_index

def _bt_python_ctf_clock_set_uuid_index(clock, index, value):
    return _nativebt._bt_python_ctf_clock_set_uuid_index(clock, index, value)
_bt_python_ctf_clock_set_uuid_index = _nativebt._bt_python_ctf_clock_set_uuid_index

def _bt_python_create_iter_pos():
    return _nativebt._bt_python_create_iter_pos()
_bt_python_create_iter_pos = _nativebt._bt_python_create_iter_pos

def _bt_python_ctf_iter_create_intersect(ctx, inter_begin_pos, inter_end_pos):
    return _nativebt._bt_python_ctf_iter_create_intersect(ctx, inter_begin_pos, inter_end_pos)
_bt_python_ctf_iter_create_intersect = _nativebt._bt_python_ctf_iter_create_intersect

def _bt_python_trace_collection_has_intersection(ctx):
    return _nativebt._bt_python_trace_collection_has_intersection(ctx)
_bt_python_trace_collection_has_intersection = _nativebt._bt_python_trace_collection_has_intersection

def _bt_context_create():
    return _nativebt._bt_context_create()
_bt_context_create = _nativebt._bt_context_create

def _bt_context_add_trace(ctx, path, format, packet_seek, stream_list, metadata):
    return _nativebt._bt_context_add_trace(ctx, path, format, packet_seek, stream_list, metadata)
_bt_context_add_trace = _nativebt._bt_context_add_trace

def _bt_context_remove_trace(ctx, trace_id):
    return _nativebt._bt_context_remove_trace(ctx, trace_id)
_bt_context_remove_trace = _nativebt._bt_context_remove_trace

def _bt_context_get(ctx):
    return _nativebt._bt_context_get(ctx)
_bt_context_get = _nativebt._bt_context_get

def _bt_context_put(ctx):
    return _nativebt._bt_context_put(ctx)
_bt_context_put = _nativebt._bt_context_put

def _bt_ctf_event_get_context(event):
    return _nativebt._bt_ctf_event_get_context(event)
_bt_ctf_event_get_context = _nativebt._bt_ctf_event_get_context

def lookup_format(qname):
    return _nativebt.lookup_format(qname)
lookup_format = _nativebt.lookup_format

def _bt_print_format_list(fp):
    return _nativebt._bt_print_format_list(fp)
_bt_print_format_list = _nativebt._bt_print_format_list

def bt_register_format(format):
    return _nativebt.bt_register_format(format)
bt_register_format = _nativebt.bt_register_format

def unregister_format(format):
    return _nativebt.unregister_format(format)
unregister_format = _nativebt.unregister_format

def _bt_iter_create(ctx, begin_pos, end_pos):
    return _nativebt._bt_iter_create(ctx, begin_pos, end_pos)
_bt_iter_create = _nativebt._bt_iter_create

def _bt_iter_destroy(iter):
    return _nativebt._bt_iter_destroy(iter)
_bt_iter_destroy = _nativebt._bt_iter_destroy

def _bt_iter_next(iter):
    return _nativebt._bt_iter_next(iter)
_bt_iter_next = _nativebt._bt_iter_next

def _bt_iter_get_pos(iter):
    return _nativebt._bt_iter_get_pos(iter)
_bt_iter_get_pos = _nativebt._bt_iter_get_pos

def _bt_iter_free_pos(pos):
    return _nativebt._bt_iter_free_pos(pos)
_bt_iter_free_pos = _nativebt._bt_iter_free_pos

def _bt_iter_set_pos(iter, pos):
    return _nativebt._bt_iter_set_pos(iter, pos)
_bt_iter_set_pos = _nativebt._bt_iter_set_pos

def _bt_iter_create_time_pos(iter, timestamp):
    return _nativebt._bt_iter_create_time_pos(iter, timestamp)
_bt_iter_create_time_pos = _nativebt._bt_iter_create_time_pos
class _bt_iter_pos(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, _bt_iter_pos, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, _bt_iter_pos, name)
    __repr__ = _swig_repr
    __swig_setmethods__["type"] = _nativebt._bt_iter_pos_type_set
    __swig_getmethods__["type"] = _nativebt._bt_iter_pos_type_get
    if _newclass:
        type = _swig_property(_nativebt._bt_iter_pos_type_get, _nativebt._bt_iter_pos_type_set)
    __swig_getmethods__["u"] = _nativebt._bt_iter_pos_u_get
    if _newclass:
        u = _swig_property(_nativebt._bt_iter_pos_u_get)

    def __init__(self):
        this = _nativebt.new__bt_iter_pos()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _nativebt.delete__bt_iter_pos
    __del__ = lambda self: None
_bt_iter_pos_swigregister = _nativebt._bt_iter_pos_swigregister
_bt_iter_pos_swigregister(_bt_iter_pos)
SEEK_TIME = _nativebt.SEEK_TIME
SEEK_RESTORE = _nativebt.SEEK_RESTORE
SEEK_CUR = _nativebt.SEEK_CUR
SEEK_BEGIN = _nativebt.SEEK_BEGIN
SEEK_LAST = _nativebt.SEEK_LAST

class bt_iter_pos_u(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, bt_iter_pos_u, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, bt_iter_pos_u, name)
    __repr__ = _swig_repr
    __swig_setmethods__["seek_time"] = _nativebt.bt_iter_pos_u_seek_time_set
    __swig_getmethods__["seek_time"] = _nativebt.bt_iter_pos_u_seek_time_get
    if _newclass:
        seek_time = _swig_property(_nativebt.bt_iter_pos_u_seek_time_get, _nativebt.bt_iter_pos_u_seek_time_set)
    __swig_setmethods__["restore"] = _nativebt.bt_iter_pos_u_restore_set
    __swig_getmethods__["restore"] = _nativebt.bt_iter_pos_u_restore_get
    if _newclass:
        restore = _swig_property(_nativebt.bt_iter_pos_u_restore_get, _nativebt.bt_iter_pos_u_restore_set)

    def __init__(self):
        this = _nativebt.new_bt_iter_pos_u()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _nativebt.delete_bt_iter_pos_u
    __del__ = lambda self: None
bt_iter_pos_u_swigregister = _nativebt.bt_iter_pos_u_swigregister
bt_iter_pos_u_swigregister(bt_iter_pos_u)


def _bt_trace_handle_create(ctx):
    return _nativebt._bt_trace_handle_create(ctx)
_bt_trace_handle_create = _nativebt._bt_trace_handle_create

def _bt_trace_handle_destroy(bt):
    return _nativebt._bt_trace_handle_destroy(bt)
_bt_trace_handle_destroy = _nativebt._bt_trace_handle_destroy

def _bt_trace_handle_get_path(ctx, handle_id):
    return _nativebt._bt_trace_handle_get_path(ctx, handle_id)
_bt_trace_handle_get_path = _nativebt._bt_trace_handle_get_path

def _bt_trace_handle_get_timestamp_begin(ctx, handle_id, type):
    return _nativebt._bt_trace_handle_get_timestamp_begin(ctx, handle_id, type)
_bt_trace_handle_get_timestamp_begin = _nativebt._bt_trace_handle_get_timestamp_begin

def _bt_trace_handle_get_timestamp_end(ctx, handle_id, type):
    return _nativebt._bt_trace_handle_get_timestamp_end(ctx, handle_id, type)
_bt_trace_handle_get_timestamp_end = _nativebt._bt_trace_handle_get_timestamp_end

def _bt_ctf_event_get_handle_id(event):
    return _nativebt._bt_ctf_event_get_handle_id(event)
_bt_ctf_event_get_handle_id = _nativebt._bt_ctf_event_get_handle_id

def _bt_ctf_iter_create(ctx, begin_pos, end_pos):
    return _nativebt._bt_ctf_iter_create(ctx, begin_pos, end_pos)
_bt_ctf_iter_create = _nativebt._bt_ctf_iter_create

def _bt_ctf_get_iter(iter):
    return _nativebt._bt_ctf_get_iter(iter)
_bt_ctf_get_iter = _nativebt._bt_ctf_get_iter

def _bt_ctf_iter_destroy(iter):
    return _nativebt._bt_ctf_iter_destroy(iter)
_bt_ctf_iter_destroy = _nativebt._bt_ctf_iter_destroy

def _bt_ctf_iter_read_event(iter):
    return _nativebt._bt_ctf_iter_read_event(iter)
_bt_ctf_iter_read_event = _nativebt._bt_ctf_iter_read_event

def _bt_ctf_get_top_level_scope(ctf_event, scope):
    return _nativebt._bt_ctf_get_top_level_scope(ctf_event, scope)
_bt_ctf_get_top_level_scope = _nativebt._bt_ctf_get_top_level_scope

def _bt_ctf_event_name(ctf_event):
    return _nativebt._bt_ctf_event_name(ctf_event)
_bt_ctf_event_name = _nativebt._bt_ctf_event_name

def _bt_ctf_get_timestamp(ctf_event):
    return _nativebt._bt_ctf_get_timestamp(ctf_event)
_bt_ctf_get_timestamp = _nativebt._bt_ctf_get_timestamp

def _bt_ctf_get_cycles(ctf_event):
    return _nativebt._bt_ctf_get_cycles(ctf_event)
_bt_ctf_get_cycles = _nativebt._bt_ctf_get_cycles

def _bt_ctf_get_field(ctf_event, scope, field):
    return _nativebt._bt_ctf_get_field(ctf_event, scope, field)
_bt_ctf_get_field = _nativebt._bt_ctf_get_field

def _bt_ctf_get_index(ctf_event, field, index):
    return _nativebt._bt_ctf_get_index(ctf_event, field, index)
_bt_ctf_get_index = _nativebt._bt_ctf_get_index

def _bt_ctf_field_name(field):
    return _nativebt._bt_ctf_field_name(field)
_bt_ctf_field_name = _nativebt._bt_ctf_field_name

def _bt_ctf_field_type(field):
    return _nativebt._bt_ctf_field_type(field)
_bt_ctf_field_type = _nativebt._bt_ctf_field_type

def _bt_ctf_get_int_signedness(field):
    return _nativebt._bt_ctf_get_int_signedness(field)
_bt_ctf_get_int_signedness = _nativebt._bt_ctf_get_int_signedness

def _bt_ctf_get_int_base(field):
    return _nativebt._bt_ctf_get_int_base(field)
_bt_ctf_get_int_base = _nativebt._bt_ctf_get_int_base

def _bt_ctf_get_int_byte_order(field):
    return _nativebt._bt_ctf_get_int_byte_order(field)
_bt_ctf_get_int_byte_order = _nativebt._bt_ctf_get_int_byte_order

def _bt_ctf_get_int_len(field):
    return _nativebt._bt_ctf_get_int_len(field)
_bt_ctf_get_int_len = _nativebt._bt_ctf_get_int_len

def _bt_ctf_get_enum_int(field):
    return _nativebt._bt_ctf_get_enum_int(field)
_bt_ctf_get_enum_int = _nativebt._bt_ctf_get_enum_int

def _bt_ctf_get_enum_str(field):
    return _nativebt._bt_ctf_get_enum_str(field)
_bt_ctf_get_enum_str = _nativebt._bt_ctf_get_enum_str

def _bt_ctf_get_encoding(field):
    return _nativebt._bt_ctf_get_encoding(field)
_bt_ctf_get_encoding = _nativebt._bt_ctf_get_encoding

def _bt_ctf_get_array_len(field):
    return _nativebt._bt_ctf_get_array_len(field)
_bt_ctf_get_array_len = _nativebt._bt_ctf_get_array_len

def _bt_array_index(array, i):
    return _nativebt._bt_array_index(array, i)
_bt_array_index = _nativebt._bt_array_index

def _bt_ctf_get_uint64(field):
    return _nativebt._bt_ctf_get_uint64(field)
_bt_ctf_get_uint64 = _nativebt._bt_ctf_get_uint64

def _bt_ctf_get_int64(field):
    return _nativebt._bt_ctf_get_int64(field)
_bt_ctf_get_int64 = _nativebt._bt_ctf_get_int64

def _bt_ctf_get_char_array(field):
    return _nativebt._bt_ctf_get_char_array(field)
_bt_ctf_get_char_array = _nativebt._bt_ctf_get_char_array

def _bt_ctf_get_string(field):
    return _nativebt._bt_ctf_get_string(field)
_bt_ctf_get_string = _nativebt._bt_ctf_get_string

def _bt_ctf_get_float(field):
    return _nativebt._bt_ctf_get_float(field)
_bt_ctf_get_float = _nativebt._bt_ctf_get_float

def _bt_ctf_get_variant(field):
    return _nativebt._bt_ctf_get_variant(field)
_bt_ctf_get_variant = _nativebt._bt_ctf_get_variant

def _bt_ctf_field_get_error():
    return _nativebt._bt_ctf_field_get_error()
_bt_ctf_field_get_error = _nativebt._bt_ctf_field_get_error

def _bt_ctf_get_decl_event_name(event):
    return _nativebt._bt_ctf_get_decl_event_name(event)
_bt_ctf_get_decl_event_name = _nativebt._bt_ctf_get_decl_event_name

def _bt_ctf_get_decl_event_id(event):
    return _nativebt._bt_ctf_get_decl_event_id(event)
_bt_ctf_get_decl_event_id = _nativebt._bt_ctf_get_decl_event_id

def _bt_ctf_get_decl_field_name(field):
    return _nativebt._bt_ctf_get_decl_field_name(field)
_bt_ctf_get_decl_field_name = _nativebt._bt_ctf_get_decl_field_name

def _bt_ctf_get_decl_from_def(field):
    return _nativebt._bt_ctf_get_decl_from_def(field)
_bt_ctf_get_decl_from_def = _nativebt._bt_ctf_get_decl_from_def

def _bt_ctf_get_decl_from_field_decl(field):
    return _nativebt._bt_ctf_get_decl_from_field_decl(field)
_bt_ctf_get_decl_from_field_decl = _nativebt._bt_ctf_get_decl_from_field_decl

def _bt_sequence_len(sequence):
    return _nativebt._bt_sequence_len(sequence)
_bt_sequence_len = _nativebt._bt_sequence_len

def _bt_sequence_index(sequence, i):
    return _nativebt._bt_sequence_index(sequence, i)
_bt_sequence_index = _nativebt._bt_sequence_index

def _bt_ctf_get_struct_field_count(structure):
    return _nativebt._bt_ctf_get_struct_field_count(structure)
_bt_ctf_get_struct_field_count = _nativebt._bt_ctf_get_struct_field_count

def _bt_ctf_get_struct_field_index(structure, i):
    return _nativebt._bt_ctf_get_struct_field_index(structure, i)
_bt_ctf_get_struct_field_index = _nativebt._bt_ctf_get_struct_field_index

def _bt_ctf_clock_create(name):
    return _nativebt._bt_ctf_clock_create(name)
_bt_ctf_clock_create = _nativebt._bt_ctf_clock_create

def _bt_ctf_clock_get_name(clock):
    return _nativebt._bt_ctf_clock_get_name(clock)
_bt_ctf_clock_get_name = _nativebt._bt_ctf_clock_get_name

def _bt_ctf_clock_get_description(clock):
    return _nativebt._bt_ctf_clock_get_description(clock)
_bt_ctf_clock_get_description = _nativebt._bt_ctf_clock_get_description

def _bt_ctf_clock_set_description(clock, desc):
    return _nativebt._bt_ctf_clock_set_description(clock, desc)
_bt_ctf_clock_set_description = _nativebt._bt_ctf_clock_set_description

def _bt_ctf_clock_get_frequency(clock):
    return _nativebt._bt_ctf_clock_get_frequency(clock)
_bt_ctf_clock_get_frequency = _nativebt._bt_ctf_clock_get_frequency

def _bt_ctf_clock_set_frequency(clock, freq):
    return _nativebt._bt_ctf_clock_set_frequency(clock, freq)
_bt_ctf_clock_set_frequency = _nativebt._bt_ctf_clock_set_frequency

def _bt_ctf_clock_get_precision(clock):
    return _nativebt._bt_ctf_clock_get_precision(clock)
_bt_ctf_clock_get_precision = _nativebt._bt_ctf_clock_get_precision

def _bt_ctf_clock_set_precision(clock, precision):
    return _nativebt._bt_ctf_clock_set_precision(clock, precision)
_bt_ctf_clock_set_precision = _nativebt._bt_ctf_clock_set_precision

def _bt_ctf_clock_get_offset_s(clock):
    return _nativebt._bt_ctf_clock_get_offset_s(clock)
_bt_ctf_clock_get_offset_s = _nativebt._bt_ctf_clock_get_offset_s

def _bt_ctf_clock_set_offset_s(clock, offset_s):
    return _nativebt._bt_ctf_clock_set_offset_s(clock, offset_s)
_bt_ctf_clock_set_offset_s = _nativebt._bt_ctf_clock_set_offset_s

def _bt_ctf_clock_get_offset(clock):
    return _nativebt._bt_ctf_clock_get_offset(clock)
_bt_ctf_clock_get_offset = _nativebt._bt_ctf_clock_get_offset

def _bt_ctf_clock_set_offset(clock, offset):
    return _nativebt._bt_ctf_clock_set_offset(clock, offset)
_bt_ctf_clock_set_offset = _nativebt._bt_ctf_clock_set_offset

def _bt_ctf_clock_get_is_absolute(clock):
    return _nativebt._bt_ctf_clock_get_is_absolute(clock)
_bt_ctf_clock_get_is_absolute = _nativebt._bt_ctf_clock_get_is_absolute

def _bt_ctf_clock_set_is_absolute(clock, is_absolute):
    return _nativebt._bt_ctf_clock_set_is_absolute(clock, is_absolute)
_bt_ctf_clock_set_is_absolute = _nativebt._bt_ctf_clock_set_is_absolute

def _bt_ctf_clock_set_time(clock, time):
    return _nativebt._bt_ctf_clock_set_time(clock, time)
_bt_ctf_clock_set_time = _nativebt._bt_ctf_clock_set_time

def _bt_ctf_clock_get(clock):
    return _nativebt._bt_ctf_clock_get(clock)
_bt_ctf_clock_get = _nativebt._bt_ctf_clock_get

def _bt_ctf_clock_put(clock):
    return _nativebt._bt_ctf_clock_put(clock)
_bt_ctf_clock_put = _nativebt._bt_ctf_clock_put

def _bt_ctf_field_type_integer_create(size):
    return _nativebt._bt_ctf_field_type_integer_create(size)
_bt_ctf_field_type_integer_create = _nativebt._bt_ctf_field_type_integer_create

def _bt_ctf_field_type_integer_get_size(integer):
    return _nativebt._bt_ctf_field_type_integer_get_size(integer)
_bt_ctf_field_type_integer_get_size = _nativebt._bt_ctf_field_type_integer_get_size

def _bt_ctf_field_type_integer_get_signed(integer):
    return _nativebt._bt_ctf_field_type_integer_get_signed(integer)
_bt_ctf_field_type_integer_get_signed = _nativebt._bt_ctf_field_type_integer_get_signed

def _bt_ctf_field_type_integer_set_signed(integer, is_signed):
    return _nativebt._bt_ctf_field_type_integer_set_signed(integer, is_signed)
_bt_ctf_field_type_integer_set_signed = _nativebt._bt_ctf_field_type_integer_set_signed

def _bt_ctf_field_type_integer_get_base(integer):
    return _nativebt._bt_ctf_field_type_integer_get_base(integer)
_bt_ctf_field_type_integer_get_base = _nativebt._bt_ctf_field_type_integer_get_base

def _bt_ctf_field_type_integer_set_base(integer, base):
    return _nativebt._bt_ctf_field_type_integer_set_base(integer, base)
_bt_ctf_field_type_integer_set_base = _nativebt._bt_ctf_field_type_integer_set_base

def _bt_ctf_field_type_integer_get_encoding(integer):
    return _nativebt._bt_ctf_field_type_integer_get_encoding(integer)
_bt_ctf_field_type_integer_get_encoding = _nativebt._bt_ctf_field_type_integer_get_encoding

def _bt_ctf_field_type_integer_set_encoding(integer, encoding):
    return _nativebt._bt_ctf_field_type_integer_set_encoding(integer, encoding)
_bt_ctf_field_type_integer_set_encoding = _nativebt._bt_ctf_field_type_integer_set_encoding

def _bt_ctf_field_type_enumeration_create(integer_container_type):
    return _nativebt._bt_ctf_field_type_enumeration_create(integer_container_type)
_bt_ctf_field_type_enumeration_create = _nativebt._bt_ctf_field_type_enumeration_create

def _bt_ctf_field_type_enumeration_get_container_type(enumeration):
    return _nativebt._bt_ctf_field_type_enumeration_get_container_type(enumeration)
_bt_ctf_field_type_enumeration_get_container_type = _nativebt._bt_ctf_field_type_enumeration_get_container_type

def _bt_ctf_field_type_enumeration_add_mapping(enumeration, name, range_start, range_end):
    return _nativebt._bt_ctf_field_type_enumeration_add_mapping(enumeration, name, range_start, range_end)
_bt_ctf_field_type_enumeration_add_mapping = _nativebt._bt_ctf_field_type_enumeration_add_mapping

def _bt_ctf_field_type_enumeration_add_mapping_unsigned(enumeration, name, range_start, range_end):
    return _nativebt._bt_ctf_field_type_enumeration_add_mapping_unsigned(enumeration, name, range_start, range_end)
_bt_ctf_field_type_enumeration_add_mapping_unsigned = _nativebt._bt_ctf_field_type_enumeration_add_mapping_unsigned

def _bt_ctf_field_type_floating_point_create():
    return _nativebt._bt_ctf_field_type_floating_point_create()
_bt_ctf_field_type_floating_point_create = _nativebt._bt_ctf_field_type_floating_point_create

def _bt_ctf_field_type_floating_point_get_exponent_digits(floating_point):
    return _nativebt._bt_ctf_field_type_floating_point_get_exponent_digits(floating_point)
_bt_ctf_field_type_floating_point_get_exponent_digits = _nativebt._bt_ctf_field_type_floating_point_get_exponent_digits

def _bt_ctf_field_type_floating_point_set_exponent_digits(floating_point, exponent_digits):
    return _nativebt._bt_ctf_field_type_floating_point_set_exponent_digits(floating_point, exponent_digits)
_bt_ctf_field_type_floating_point_set_exponent_digits = _nativebt._bt_ctf_field_type_floating_point_set_exponent_digits

def _bt_ctf_field_type_floating_point_get_mantissa_digits(floating_point):
    return _nativebt._bt_ctf_field_type_floating_point_get_mantissa_digits(floating_point)
_bt_ctf_field_type_floating_point_get_mantissa_digits = _nativebt._bt_ctf_field_type_floating_point_get_mantissa_digits

def _bt_ctf_field_type_floating_point_set_mantissa_digits(floating_point, mantissa_digits):
    return _nativebt._bt_ctf_field_type_floating_point_set_mantissa_digits(floating_point, mantissa_digits)
_bt_ctf_field_type_floating_point_set_mantissa_digits = _nativebt._bt_ctf_field_type_floating_point_set_mantissa_digits

def _bt_ctf_field_type_structure_create():
    return _nativebt._bt_ctf_field_type_structure_create()
_bt_ctf_field_type_structure_create = _nativebt._bt_ctf_field_type_structure_create

def _bt_ctf_field_type_structure_add_field(structure, field_type, field_name):
    return _nativebt._bt_ctf_field_type_structure_add_field(structure, field_type, field_name)
_bt_ctf_field_type_structure_add_field = _nativebt._bt_ctf_field_type_structure_add_field

def _bt_ctf_field_type_structure_get_field_count(structure):
    return _nativebt._bt_ctf_field_type_structure_get_field_count(structure)
_bt_ctf_field_type_structure_get_field_count = _nativebt._bt_ctf_field_type_structure_get_field_count

def _bt_ctf_field_type_structure_get_field(structure, arg2, arg3, index):
    return _nativebt._bt_ctf_field_type_structure_get_field(structure, arg2, arg3, index)
_bt_ctf_field_type_structure_get_field = _nativebt._bt_ctf_field_type_structure_get_field

def _bt_ctf_field_type_structure_get_field_type_by_name(structure, field_name):
    return _nativebt._bt_ctf_field_type_structure_get_field_type_by_name(structure, field_name)
_bt_ctf_field_type_structure_get_field_type_by_name = _nativebt._bt_ctf_field_type_structure_get_field_type_by_name

def _bt_ctf_field_type_variant_create(enum_tag, tag_name):
    return _nativebt._bt_ctf_field_type_variant_create(enum_tag, tag_name)
_bt_ctf_field_type_variant_create = _nativebt._bt_ctf_field_type_variant_create

def _bt_ctf_field_type_variant_get_tag_type(variant):
    return _nativebt._bt_ctf_field_type_variant_get_tag_type(variant)
_bt_ctf_field_type_variant_get_tag_type = _nativebt._bt_ctf_field_type_variant_get_tag_type

def _bt_ctf_field_type_variant_get_tag_name(variant):
    return _nativebt._bt_ctf_field_type_variant_get_tag_name(variant)
_bt_ctf_field_type_variant_get_tag_name = _nativebt._bt_ctf_field_type_variant_get_tag_name

def _bt_ctf_field_type_variant_add_field(variant, field_type, field_name):
    return _nativebt._bt_ctf_field_type_variant_add_field(variant, field_type, field_name)
_bt_ctf_field_type_variant_add_field = _nativebt._bt_ctf_field_type_variant_add_field

def _bt_ctf_field_type_variant_get_field_type_by_name(variant, field_name):
    return _nativebt._bt_ctf_field_type_variant_get_field_type_by_name(variant, field_name)
_bt_ctf_field_type_variant_get_field_type_by_name = _nativebt._bt_ctf_field_type_variant_get_field_type_by_name

def _bt_ctf_field_type_variant_get_field_type_from_tag(variant, tag):
    return _nativebt._bt_ctf_field_type_variant_get_field_type_from_tag(variant, tag)
_bt_ctf_field_type_variant_get_field_type_from_tag = _nativebt._bt_ctf_field_type_variant_get_field_type_from_tag

def _bt_ctf_field_type_variant_get_field_count(variant):
    return _nativebt._bt_ctf_field_type_variant_get_field_count(variant)
_bt_ctf_field_type_variant_get_field_count = _nativebt._bt_ctf_field_type_variant_get_field_count

def _bt_ctf_field_type_variant_get_field(variant, arg2, arg3, index):
    return _nativebt._bt_ctf_field_type_variant_get_field(variant, arg2, arg3, index)
_bt_ctf_field_type_variant_get_field = _nativebt._bt_ctf_field_type_variant_get_field

def _bt_ctf_field_type_array_create(element_type, length):
    return _nativebt._bt_ctf_field_type_array_create(element_type, length)
_bt_ctf_field_type_array_create = _nativebt._bt_ctf_field_type_array_create

def _bt_ctf_field_type_array_get_element_type(array):
    return _nativebt._bt_ctf_field_type_array_get_element_type(array)
_bt_ctf_field_type_array_get_element_type = _nativebt._bt_ctf_field_type_array_get_element_type

def _bt_ctf_field_type_array_get_length(array):
    return _nativebt._bt_ctf_field_type_array_get_length(array)
_bt_ctf_field_type_array_get_length = _nativebt._bt_ctf_field_type_array_get_length

def _bt_ctf_field_type_sequence_create(element_type, length_field_name):
    return _nativebt._bt_ctf_field_type_sequence_create(element_type, length_field_name)
_bt_ctf_field_type_sequence_create = _nativebt._bt_ctf_field_type_sequence_create

def _bt_ctf_field_type_sequence_get_element_type(sequence):
    return _nativebt._bt_ctf_field_type_sequence_get_element_type(sequence)
_bt_ctf_field_type_sequence_get_element_type = _nativebt._bt_ctf_field_type_sequence_get_element_type

def _bt_ctf_field_type_sequence_get_length_field_name(sequence):
    return _nativebt._bt_ctf_field_type_sequence_get_length_field_name(sequence)
_bt_ctf_field_type_sequence_get_length_field_name = _nativebt._bt_ctf_field_type_sequence_get_length_field_name

def _bt_ctf_field_type_string_create():
    return _nativebt._bt_ctf_field_type_string_create()
_bt_ctf_field_type_string_create = _nativebt._bt_ctf_field_type_string_create

def _bt_ctf_field_type_string_get_encoding(string_type):
    return _nativebt._bt_ctf_field_type_string_get_encoding(string_type)
_bt_ctf_field_type_string_get_encoding = _nativebt._bt_ctf_field_type_string_get_encoding

def _bt_ctf_field_type_string_set_encoding(string_type, encoding):
    return _nativebt._bt_ctf_field_type_string_set_encoding(string_type, encoding)
_bt_ctf_field_type_string_set_encoding = _nativebt._bt_ctf_field_type_string_set_encoding

def _bt_ctf_field_type_get_alignment(type):
    return _nativebt._bt_ctf_field_type_get_alignment(type)
_bt_ctf_field_type_get_alignment = _nativebt._bt_ctf_field_type_get_alignment

def _bt_ctf_field_type_set_alignment(type, alignment):
    return _nativebt._bt_ctf_field_type_set_alignment(type, alignment)
_bt_ctf_field_type_set_alignment = _nativebt._bt_ctf_field_type_set_alignment

def _bt_ctf_field_type_get_byte_order(type):
    return _nativebt._bt_ctf_field_type_get_byte_order(type)
_bt_ctf_field_type_get_byte_order = _nativebt._bt_ctf_field_type_get_byte_order

def _bt_ctf_field_type_set_byte_order(type, byte_order):
    return _nativebt._bt_ctf_field_type_set_byte_order(type, byte_order)
_bt_ctf_field_type_set_byte_order = _nativebt._bt_ctf_field_type_set_byte_order

def _bt_ctf_field_type_get_type_id(type):
    return _nativebt._bt_ctf_field_type_get_type_id(type)
_bt_ctf_field_type_get_type_id = _nativebt._bt_ctf_field_type_get_type_id

def _bt_ctf_field_type_get(type):
    return _nativebt._bt_ctf_field_type_get(type)
_bt_ctf_field_type_get = _nativebt._bt_ctf_field_type_get

def _bt_ctf_field_type_put(type):
    return _nativebt._bt_ctf_field_type_put(type)
_bt_ctf_field_type_put = _nativebt._bt_ctf_field_type_put

def _bt_ctf_field_create(type):
    return _nativebt._bt_ctf_field_create(type)
_bt_ctf_field_create = _nativebt._bt_ctf_field_create

def _bt_ctf_field_structure_get_field(structure, name):
    return _nativebt._bt_ctf_field_structure_get_field(structure, name)
_bt_ctf_field_structure_get_field = _nativebt._bt_ctf_field_structure_get_field

def _bt_ctf_field_array_get_field(array, index):
    return _nativebt._bt_ctf_field_array_get_field(array, index)
_bt_ctf_field_array_get_field = _nativebt._bt_ctf_field_array_get_field

def _bt_ctf_field_sequence_get_length(sequence):
    return _nativebt._bt_ctf_field_sequence_get_length(sequence)
_bt_ctf_field_sequence_get_length = _nativebt._bt_ctf_field_sequence_get_length

def _bt_ctf_field_sequence_set_length(sequence, length_field):
    return _nativebt._bt_ctf_field_sequence_set_length(sequence, length_field)
_bt_ctf_field_sequence_set_length = _nativebt._bt_ctf_field_sequence_set_length

def _bt_ctf_field_sequence_get_field(sequence, index):
    return _nativebt._bt_ctf_field_sequence_get_field(sequence, index)
_bt_ctf_field_sequence_get_field = _nativebt._bt_ctf_field_sequence_get_field

def _bt_ctf_field_variant_get_field(variant, tag):
    return _nativebt._bt_ctf_field_variant_get_field(variant, tag)
_bt_ctf_field_variant_get_field = _nativebt._bt_ctf_field_variant_get_field

def _bt_ctf_field_enumeration_get_container(enumeration):
    return _nativebt._bt_ctf_field_enumeration_get_container(enumeration)
_bt_ctf_field_enumeration_get_container = _nativebt._bt_ctf_field_enumeration_get_container

def _bt_ctf_field_signed_integer_get_value(integer):
    return _nativebt._bt_ctf_field_signed_integer_get_value(integer)
_bt_ctf_field_signed_integer_get_value = _nativebt._bt_ctf_field_signed_integer_get_value

def _bt_ctf_field_signed_integer_set_value(integer, value):
    return _nativebt._bt_ctf_field_signed_integer_set_value(integer, value)
_bt_ctf_field_signed_integer_set_value = _nativebt._bt_ctf_field_signed_integer_set_value

def _bt_ctf_field_unsigned_integer_get_value(integer):
    return _nativebt._bt_ctf_field_unsigned_integer_get_value(integer)
_bt_ctf_field_unsigned_integer_get_value = _nativebt._bt_ctf_field_unsigned_integer_get_value

def _bt_ctf_field_unsigned_integer_set_value(integer, value):
    return _nativebt._bt_ctf_field_unsigned_integer_set_value(integer, value)
_bt_ctf_field_unsigned_integer_set_value = _nativebt._bt_ctf_field_unsigned_integer_set_value

def _bt_ctf_field_floating_point_get_value(floating_point):
    return _nativebt._bt_ctf_field_floating_point_get_value(floating_point)
_bt_ctf_field_floating_point_get_value = _nativebt._bt_ctf_field_floating_point_get_value

def _bt_ctf_field_floating_point_set_value(floating_point, value):
    return _nativebt._bt_ctf_field_floating_point_set_value(floating_point, value)
_bt_ctf_field_floating_point_set_value = _nativebt._bt_ctf_field_floating_point_set_value

def _bt_ctf_field_string_get_value(string_field):
    return _nativebt._bt_ctf_field_string_get_value(string_field)
_bt_ctf_field_string_get_value = _nativebt._bt_ctf_field_string_get_value

def _bt_ctf_field_string_set_value(string_field, value):
    return _nativebt._bt_ctf_field_string_set_value(string_field, value)
_bt_ctf_field_string_set_value = _nativebt._bt_ctf_field_string_set_value

def _bt_ctf_field_get_type(field):
    return _nativebt._bt_ctf_field_get_type(field)
_bt_ctf_field_get_type = _nativebt._bt_ctf_field_get_type

def _bt_ctf_field_get(field):
    return _nativebt._bt_ctf_field_get(field)
_bt_ctf_field_get = _nativebt._bt_ctf_field_get

def _bt_ctf_field_put(field):
    return _nativebt._bt_ctf_field_put(field)
_bt_ctf_field_put = _nativebt._bt_ctf_field_put

def _bt_ctf_event_class_create(name):
    return _nativebt._bt_ctf_event_class_create(name)
_bt_ctf_event_class_create = _nativebt._bt_ctf_event_class_create

def _bt_ctf_event_class_get_name(event_class):
    return _nativebt._bt_ctf_event_class_get_name(event_class)
_bt_ctf_event_class_get_name = _nativebt._bt_ctf_event_class_get_name

def _bt_ctf_event_class_get_id(event_class):
    return _nativebt._bt_ctf_event_class_get_id(event_class)
_bt_ctf_event_class_get_id = _nativebt._bt_ctf_event_class_get_id

def _bt_ctf_event_class_set_id(event_class, id):
    return _nativebt._bt_ctf_event_class_set_id(event_class, id)
_bt_ctf_event_class_set_id = _nativebt._bt_ctf_event_class_set_id

def _bt_ctf_event_class_get_stream_class(event_class):
    return _nativebt._bt_ctf_event_class_get_stream_class(event_class)
_bt_ctf_event_class_get_stream_class = _nativebt._bt_ctf_event_class_get_stream_class

def _bt_ctf_event_class_add_field(event_class, type, name):
    return _nativebt._bt_ctf_event_class_add_field(event_class, type, name)
_bt_ctf_event_class_add_field = _nativebt._bt_ctf_event_class_add_field

def _bt_ctf_event_class_get_field_count(event_class):
    return _nativebt._bt_ctf_event_class_get_field_count(event_class)
_bt_ctf_event_class_get_field_count = _nativebt._bt_ctf_event_class_get_field_count

def _bt_ctf_event_class_get_field(event_class, field_name, field_type, index):
    return _nativebt._bt_ctf_event_class_get_field(event_class, field_name, field_type, index)
_bt_ctf_event_class_get_field = _nativebt._bt_ctf_event_class_get_field

def _bt_ctf_event_class_get_field_by_name(event_class, name):
    return _nativebt._bt_ctf_event_class_get_field_by_name(event_class, name)
_bt_ctf_event_class_get_field_by_name = _nativebt._bt_ctf_event_class_get_field_by_name

def _bt_ctf_event_class_get(event_class):
    return _nativebt._bt_ctf_event_class_get(event_class)
_bt_ctf_event_class_get = _nativebt._bt_ctf_event_class_get

def _bt_ctf_event_class_put(event_class):
    return _nativebt._bt_ctf_event_class_put(event_class)
_bt_ctf_event_class_put = _nativebt._bt_ctf_event_class_put

def _bt_ctf_event_create(event_class):
    return _nativebt._bt_ctf_event_create(event_class)
_bt_ctf_event_create = _nativebt._bt_ctf_event_create

def _bt_ctf_event_get_class(event):
    return _nativebt._bt_ctf_event_get_class(event)
_bt_ctf_event_get_class = _nativebt._bt_ctf_event_get_class

def _bt_ctf_event_get_payload(event, name):
    return _nativebt._bt_ctf_event_get_payload(event, name)
_bt_ctf_event_get_payload = _nativebt._bt_ctf_event_get_payload

def _bt_ctf_event_set_payload(event, name, value):
    return _nativebt._bt_ctf_event_set_payload(event, name, value)
_bt_ctf_event_set_payload = _nativebt._bt_ctf_event_set_payload

def _bt_ctf_event_get_payload_by_index(event, index):
    return _nativebt._bt_ctf_event_get_payload_by_index(event, index)
_bt_ctf_event_get_payload_by_index = _nativebt._bt_ctf_event_get_payload_by_index

def _bt_ctf_event_get(event):
    return _nativebt._bt_ctf_event_get(event)
_bt_ctf_event_get = _nativebt._bt_ctf_event_get

def _bt_ctf_event_put(event):
    return _nativebt._bt_ctf_event_put(event)
_bt_ctf_event_put = _nativebt._bt_ctf_event_put

def _bt_ctf_event_get_stream_event_context(event):
    return _nativebt._bt_ctf_event_get_stream_event_context(event)
_bt_ctf_event_get_stream_event_context = _nativebt._bt_ctf_event_get_stream_event_context

def _bt_ctf_event_set_stream_event_context(event, stream_event_context):
    return _nativebt._bt_ctf_event_set_stream_event_context(event, stream_event_context)
_bt_ctf_event_set_stream_event_context = _nativebt._bt_ctf_event_set_stream_event_context

def _bt_ctf_stream_class_create(name):
    return _nativebt._bt_ctf_stream_class_create(name)
_bt_ctf_stream_class_create = _nativebt._bt_ctf_stream_class_create

def _bt_ctf_stream_class_get_name(stream_class):
    return _nativebt._bt_ctf_stream_class_get_name(stream_class)
_bt_ctf_stream_class_get_name = _nativebt._bt_ctf_stream_class_get_name

def _bt_ctf_stream_class_get_clock(stream_class):
    return _nativebt._bt_ctf_stream_class_get_clock(stream_class)
_bt_ctf_stream_class_get_clock = _nativebt._bt_ctf_stream_class_get_clock

def _bt_ctf_stream_class_set_clock(stream_class, clock):
    return _nativebt._bt_ctf_stream_class_set_clock(stream_class, clock)
_bt_ctf_stream_class_set_clock = _nativebt._bt_ctf_stream_class_set_clock

def _bt_ctf_stream_class_get_id(stream_class):
    return _nativebt._bt_ctf_stream_class_get_id(stream_class)
_bt_ctf_stream_class_get_id = _nativebt._bt_ctf_stream_class_get_id

def _bt_ctf_stream_class_set_id(stream_class, id):
    return _nativebt._bt_ctf_stream_class_set_id(stream_class, id)
_bt_ctf_stream_class_set_id = _nativebt._bt_ctf_stream_class_set_id

def _bt_ctf_stream_class_add_event_class(stream_class, event_class):
    return _nativebt._bt_ctf_stream_class_add_event_class(stream_class, event_class)
_bt_ctf_stream_class_add_event_class = _nativebt._bt_ctf_stream_class_add_event_class

def _bt_ctf_stream_class_get_event_class_count(stream_class):
    return _nativebt._bt_ctf_stream_class_get_event_class_count(stream_class)
_bt_ctf_stream_class_get_event_class_count = _nativebt._bt_ctf_stream_class_get_event_class_count

def _bt_ctf_stream_class_get_event_class(stream_class, index):
    return _nativebt._bt_ctf_stream_class_get_event_class(stream_class, index)
_bt_ctf_stream_class_get_event_class = _nativebt._bt_ctf_stream_class_get_event_class

def _bt_ctf_stream_class_get_event_class_by_name(stream_class, name):
    return _nativebt._bt_ctf_stream_class_get_event_class_by_name(stream_class, name)
_bt_ctf_stream_class_get_event_class_by_name = _nativebt._bt_ctf_stream_class_get_event_class_by_name

def _bt_ctf_stream_class_get_packet_context_type(stream_class):
    return _nativebt._bt_ctf_stream_class_get_packet_context_type(stream_class)
_bt_ctf_stream_class_get_packet_context_type = _nativebt._bt_ctf_stream_class_get_packet_context_type

def _bt_ctf_stream_class_set_packet_context_type(stream_class, packet_context_type):
    return _nativebt._bt_ctf_stream_class_set_packet_context_type(stream_class, packet_context_type)
_bt_ctf_stream_class_set_packet_context_type = _nativebt._bt_ctf_stream_class_set_packet_context_type

def _bt_ctf_stream_class_get_event_context_type(stream_class):
    return _nativebt._bt_ctf_stream_class_get_event_context_type(stream_class)
_bt_ctf_stream_class_get_event_context_type = _nativebt._bt_ctf_stream_class_get_event_context_type

def _bt_ctf_stream_class_set_event_context_type(stream_class, event_context_type):
    return _nativebt._bt_ctf_stream_class_set_event_context_type(stream_class, event_context_type)
_bt_ctf_stream_class_set_event_context_type = _nativebt._bt_ctf_stream_class_set_event_context_type

def _bt_ctf_stream_class_get(stream_class):
    return _nativebt._bt_ctf_stream_class_get(stream_class)
_bt_ctf_stream_class_get = _nativebt._bt_ctf_stream_class_get

def _bt_ctf_stream_class_put(stream_class):
    return _nativebt._bt_ctf_stream_class_put(stream_class)
_bt_ctf_stream_class_put = _nativebt._bt_ctf_stream_class_put

def _bt_ctf_stream_get_discarded_events_count(stream):
    return _nativebt._bt_ctf_stream_get_discarded_events_count(stream)
_bt_ctf_stream_get_discarded_events_count = _nativebt._bt_ctf_stream_get_discarded_events_count

def _bt_ctf_stream_append_discarded_events(stream, event_count):
    return _nativebt._bt_ctf_stream_append_discarded_events(stream, event_count)
_bt_ctf_stream_append_discarded_events = _nativebt._bt_ctf_stream_append_discarded_events

def _bt_ctf_stream_append_event(stream, event):
    return _nativebt._bt_ctf_stream_append_event(stream, event)
_bt_ctf_stream_append_event = _nativebt._bt_ctf_stream_append_event

def _bt_ctf_stream_get_packet_context(stream):
    return _nativebt._bt_ctf_stream_get_packet_context(stream)
_bt_ctf_stream_get_packet_context = _nativebt._bt_ctf_stream_get_packet_context

def _bt_ctf_stream_set_packet_context(stream, packet_context):
    return _nativebt._bt_ctf_stream_set_packet_context(stream, packet_context)
_bt_ctf_stream_set_packet_context = _nativebt._bt_ctf_stream_set_packet_context

def _bt_ctf_stream_flush(stream):
    return _nativebt._bt_ctf_stream_flush(stream)
_bt_ctf_stream_flush = _nativebt._bt_ctf_stream_flush

def _bt_ctf_stream_get(stream):
    return _nativebt._bt_ctf_stream_get(stream)
_bt_ctf_stream_get = _nativebt._bt_ctf_stream_get

def _bt_ctf_stream_put(stream):
    return _nativebt._bt_ctf_stream_put(stream)
_bt_ctf_stream_put = _nativebt._bt_ctf_stream_put

def _bt_ctf_writer_create(path):
    return _nativebt._bt_ctf_writer_create(path)
_bt_ctf_writer_create = _nativebt._bt_ctf_writer_create

def _bt_ctf_writer_create_stream(writer, stream_class):
    return _nativebt._bt_ctf_writer_create_stream(writer, stream_class)
_bt_ctf_writer_create_stream = _nativebt._bt_ctf_writer_create_stream

def _bt_ctf_writer_add_environment_field(writer, name, value):
    return _nativebt._bt_ctf_writer_add_environment_field(writer, name, value)
_bt_ctf_writer_add_environment_field = _nativebt._bt_ctf_writer_add_environment_field

def _bt_ctf_writer_add_environment_field_int64(writer, name, value):
    return _nativebt._bt_ctf_writer_add_environment_field_int64(writer, name, value)
_bt_ctf_writer_add_environment_field_int64 = _nativebt._bt_ctf_writer_add_environment_field_int64

def _bt_ctf_writer_add_clock(writer, clock):
    return _nativebt._bt_ctf_writer_add_clock(writer, clock)
_bt_ctf_writer_add_clock = _nativebt._bt_ctf_writer_add_clock

def _bt_ctf_writer_get_metadata_string(writer):
    return _nativebt._bt_ctf_writer_get_metadata_string(writer)
_bt_ctf_writer_get_metadata_string = _nativebt._bt_ctf_writer_get_metadata_string

def _bt_ctf_writer_flush_metadata(writer):
    return _nativebt._bt_ctf_writer_flush_metadata(writer)
_bt_ctf_writer_flush_metadata = _nativebt._bt_ctf_writer_flush_metadata

def _bt_ctf_writer_set_byte_order(writer, byte_order):
    return _nativebt._bt_ctf_writer_set_byte_order(writer, byte_order)
_bt_ctf_writer_set_byte_order = _nativebt._bt_ctf_writer_set_byte_order

def _bt_ctf_writer_get(writer):
    return _nativebt._bt_ctf_writer_get(writer)
_bt_ctf_writer_get = _nativebt._bt_ctf_writer_get

def _bt_ctf_writer_put(writer):
    return _nativebt._bt_ctf_writer_put(writer)
_bt_ctf_writer_put = _nativebt._bt_ctf_writer_put
# This file is compatible with both classic and new-style classes.


